[package]
name = "pi-http"
version = "0.1.16"
edition = "2024"
rust-version = "1.85"
license-file = "../../LICENSE"

[lib]
name = "pi_http"
path = "src/lib.rs"
test = false
doctest = false

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
memchr = { workspace = true }
pi-core = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls", "stream"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, features = ["raw_value"] }
sha2 = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
